"""Complete betting dashboard

Revision ID: 53c750855b53
Revises: c368cbe49958
Create Date: 2026-07-22 18:42:34.844902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c750855b53'
down_revision = 'c368cbe49958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bettor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bettor_id'], ['bettors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bettor_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['bettor_id'], ['bettors.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gross_winnings', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_returned', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_column('total_returned')
        batch_op.drop_column('net_profit')
        batch_op.drop_column('commission_amount')
        batch_op.drop_column('gross_winnings')

    op.drop_table('ledger_entries')
    op.drop_table('payments')
    # ### end Alembic commands ###
