"""Create fights table

Revision ID: c877f21fdcd0
Revises: 
Create Date: 2026-07-22 18:27:06.151993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c877f21fdcd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_a', sa.String(length=120), nullable=False),
    sa.Column('fighter_b', sa.String(length=120), nullable=False),
    sa.Column('fight_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('winner_side', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fights')
    # ### end Alembic commands ###
